### ISSUE TITLE
Add timeouts to all HTTP requests

### ISSUE THREAD

**Issue by teeberg** [smeggingsmegger/PyBambooHR#33]
Like the [`requests` docs](http://docs.python-requests.org/en/master/user/quickstart/#timeouts) say:
> You can tell Requests to stop waiting for a response after a given number of seconds with the timeout parameter. Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely:

Bringing this up because our code just got stuck trying to fetch an employee's photo in [`get_employee_photo`](https://github.com/smeggingsmegger/PyBambooHR/blob/9775a55a844b4dbc247b03b23e57d5828cef7e58/PyBambooHR/PyBambooHR.py#L307-L322) and didn't raise an exception until it was killed by celery.

**Comment by imarban** [comment]
I can take this one. I don't know if @smeggingsmegger is still contributing to this, otherwise I will fork the project and work there.

**Comment by smeggingsmegger** [comment]
@imarban I'm still working on it. Please feel free to send me a PR! :)

**Comment by imarban** [comment]
@smeggingsmegger @teeberg What do you think is a good value for timeout? I am asking you guys since you are more familiar with BambooHR API. I just started to play with it. 30 secs?

**Comment by teeberg** [comment]
@imarban It's not trivial to say without measuring how long bamboo takes for some big responses, but I think arbitrary 30 seconds to connect and 5 minutes to read should cover all valid scenarios.

**Comment by teeberg** [comment]
maybe it's also not any one's call to make. how about giving `PyBambooHr()` an additional `timeout` field that propagates down?

**Comment by smeggingsmegger** [comment]
I've added a keyword argument "timeout" to init that lets you override a timeout value. It's set to 60 seconds by default so you'll want to adjust that accordingly for yourself.

**Comment by teeberg** [comment]
For posterity, that argument was added in https://github.com/smeggingsmegger/PyBambooHR/commit/e5f6e7397910033d4b52c13a6fb57c6201e74246
