### ISSUE TITLE
Custom Fields in get_employee

### ISSUE THREAD

**Issue by horida** [smeggingsmegger/PyBambooHR#54]
The `get_employee` method does not support custom fields but throws 

    UserWarning: You passed in an invalid field

Issue #28 only fixes it for `request_custom_support`.

This PR fixes this for `get_employee` as well https://github.com/smeggingsmegger/PyBambooHR/pull/53 .

**Comment by horida** [comment]
@smeggingsmegger any chance to get this approved soon? Is a new release planned?
Thanks!

**Comment by kiarafbickers** [comment]
Same question. https://github.com/smeggingsmegger/PyBambooHR/issues/59

**Comment by smeggingsmegger** [comment]
@kiarafbickers @horida I’ve merged that PR and added horida as a collaborator. I currently don’t have the bandwidth to maintain this library so the help would be appreciated. Thank you!

@horida please let me know when you’d like me to push a release and I’ll take care of it.

**Comment by horida** [comment]
Please go ahead with the release @smeggingsmegger 
Thanks a lot!!
