### ISSUE TITLE
How to make get_employee() call with custom fields

### ISSUE THREAD

**Issue by Lightblash** [smeggingsmegger/PyBambooHR#69]
Hello everyone!

I know that you added support for making get_employee() function call with custom fields. But still don't understand how to get custom fields aliases for passing to get_employee() function. I can see in metadata my custom fields but there are no aliases for them(  I have no idea how to get **custom fields names** which I should pass in get_employee() function. Please help.

Thanks!

**Comment by anttipalsola** [comment]
@Lightblash The custom field alias is the field name in camel case prefixed with "custom". For example, `Field Name` becomes `customFieldName`. In case there are duplicate names, a numeric suffix is appended (e.g. `customFieldName1`).

See #53 and https://web.archive.org/web/20160611131000/http://www.bamboohr.com/api/documentation/employees.php . For some reason, the current version of the BambooHR API documentation does not include this piece of information anymore but nevertheless it still seems to work.

**Comment by Lightblash** [comment]
@anttipalsola I tried and it works. Many thanks!
